#include<stdio.h>
#include<math.h>
#define EPSILON 0.00001

/*Question 45
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
*/

long  isInteger(double num) {
//Test if num is an integer by subtracting it from the closest int to it and comparing that number to 0.00001
	if((fabs(num - floor(num)) < EPSILON) || (fabs(num - ceil(num)) < EPSILON)) {
		return 1;
	}
	return 0;
}

long  getTriNumber(long  num) {
	return (num * (num + 1))/2;
}

long  isHexNum(long  num) {
/* If we expand and multiply the hexagonal equation we get 0 = 2n^2 - n - Hn
 * So a = 2, b = -1 and c = -Pn (Pn will be equal to num in this function)
 * and with this information we can use the quadratic formula to solve for n and if n is an integer we have a hexagonal number
*/
	double soln;
	const long  a = 2, b = -1;
	long  c = num * -1;
	soln = (double)((b * -1) + (double)sqrt(b * b - (4 * a * c)))/(2 * a);  //Quadratic Formula
	return isInteger(soln);
}
	
long  isPentNum(long  num) {
/* If we expand and multiply the pentagonal equation we get 0 = 3n^2 - n - 2Pn
 * So a = 3, b = -1 and c = -2Pn (Pn will be equal to num in this function)
 * and with this information we can use the quadratic formula to solve for n and if n is an integer we have a pentagonal number
*/
	double soln1;
	const long  a = 3, b = -1;
	long  c = num * -2;;
	soln1 = (double)((b * -1) + (double)sqrt(b * b - (4 * a * c)))/(2 * a);  //Quadratic Formula
	return isInteger(soln1);
}

int main() {
	unsigned long  currentTriangleNum;
	unsigned long  currentAnswer;
	for(currentTriangleNum = 286; ; ++currentTriangleNum) {  //Start at 286 since we know we need to find a number > 285
		currentAnswer = getTriNumber(currentTriangleNum); //Get the triangle number of the current test case
		if(isPentNum(currentAnswer) && isHexNum(currentAnswer)) {
			printf("%ld\n", currentAnswer);
			break;
		}
	}
	return 0;
}
